# -*- coding: utf-8 -*-
"""ai_model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dI0D7PTUj33xonaEpAWWEL-OorErxsF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# For preprocessing and modeling
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MultiLabelBinarizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
# Set style for seaborn
sns.set(style="whitegrid")
# Load the dataset
data = pd.read_csv("/content/drive/MyDrive/AI-based Career Recommendation System.csv")
data.head()

print("Dataset Shape:", data.shape)
print("\nDataset Info:")
data.info()

# Display summary statistics for numeric columns
data.describe()

plt.figure(figsize=(10, 6))
sns.countplot(y="Recommended_Career", data=data, order=data["Recommended_Career"].value_counts().index, palette="Set3")
plt.title("Distribution of Recommended Careers")
plt.xlabel("Count")
plt.ylabel("Recommended Career")
plt.show()

plt.figure(figsize=(8, 4))
sns.histplot(data['Recommendation_Score'], bins=10, kde=True, color="olive")
plt.title("Recommendation Score Distribution")
plt.xlabel("Recommendation Score")
plt.ylabel("Frequency")
plt.show()

# Function to split semicolon-separated values and count occurrences
def count_items(series):
    items = series.dropna().apply(lambda x: x.split(";"))
    flat_list = [item.strip() for sublist in items for item in sublist]
    return pd.Series(flat_list).value_counts()

# Count Skills
skills_count = count_items(data["Skills"])
print("Most common skills:\n", skills_count)

# Plot skills count
plt.figure(figsize=(10, 4))
sns.barplot(x=skills_count.index, y=skills_count.values, palette="viridis")
plt.xticks(rotation=45)
plt.title("Skill Frequencies")
plt.xlabel("Skill")
plt.ylabel("Frequency")
plt.show()

# Plot as horizontal bars with more vertical space
plt.figure(figsize=(18, 14))  # taller figure
sns.barplot(x=skills_count.values, y=skills_count.index, palette="viridis")
plt.title("Skill Frequencies")
plt.xlabel("Frequency")
plt.ylabel("Skill")
plt.tight_layout()  # prevents clipping of labels
plt.show()

# Count Interests
interests_count = count_items(data["Interests"])
print("Most common interests:\n", interests_count)

# Plot interests count as horizontal bars
plt.figure(figsize=(12, 8))
sns.barplot(x=interests_count.values, y=interests_count.index, palette="magma")
plt.title("Interest Frequencies")
plt.xlabel("Frequency")
plt.ylabel("Interest")
plt.tight_layout()
plt.show()

"""Our goal is to build a model to predict Recommended_Career based on candidate features.
Feature Selection
We will use:

Age (numeric)
Education (categorical, will be label-encoded)
Skills and Interests (text fields, which we will vectorize)
We will drop columns like CandidateID and Name as they are identifiers and not useful for prediction.
"""

# Select features and target variable
features = data[['Age', 'Education', 'Skills', 'Interests']]
target = data['Recommended_Career']

edu_encoder = LabelEncoder()
features['Education_enc'] = edu_encoder.fit_transform(features['Education'])
features.head()

# Create a combined text column
features['Text_Features'] = features['Skills'].fillna('') + " " + features['Interests'].fillna('')

# Use CountVectorizer for text feature extraction
vectorizer = CountVectorizer(tokenizer=lambda x: [item.strip() for item in x.split(";") if item.strip()],
                             lowercase=True)
text_features = vectorizer.fit_transform(features['Text_Features'])

print("Shape of text features:", text_features.shape)

from scipy.sparse import hstack

# Create a numeric matrix from Age and Education_enc
numeric_features = features[['Age', 'Education_enc']].values

# hstack to combine the numeric features with the text features
from scipy import sparse
X = hstack([sparse.csr_matrix(numeric_features), text_features])

# Encode target variable
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(target)

print("Feature matrix shape:", X.shape)
print("Target classes:", target_encoder.classes_)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=target_encoder.classes_,
            yticklabels=target_encoder.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()
